GET http://localhost:3000/products

###
GET http://localhost:3000/products/f4b6b8bb-7258-43d1-9d45-7646a3fb2a69

###
GET http://localhost:3000/products/tv-32


###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "tv 32",
  "description": "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. In elementis mé pra quem é amistosis quis leo. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. Cevadis im ampola pa arma uma pindureta.",
  "image_url": "https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218fHx8fHx8fHwxNjIzMzQ0NjY2&ixlib=rb-1.2.1&q=80&w=1080&utm_source=unsplash_source&utm_medium=referral&utm_campaign=api-credit",
  "price": 1500.99
}


###
PATCH http://localhost:3000/products/f4b6b8bb-7258-43d1-9d45-7646a3fb2a69
Content-Type: application/json

{
  "name": "tv 32 alterada de novo",
  "price": 1400.99
}

###
DELETE http://localhost:3000/products/f4b6b8bb-7258-43d1-9d45-7646a3fb2a69
